import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import NavBar from "@/components/Navbar/NavBar";
import Footer from "@/components/Footer/Footer";
import Homepage from "@/components/Homepage/Homepage";
import About from "@/components/About/About";
import Admission from "@/components/Admission/Admission";
import Department from "@/components/Department/Department";
import Achivement from "@/components/Achivements/Achivement";
import Contact from "@/components/Contact/Contact";
import Notes from "@/components/Notes/Notes";
import Galary from "@/components/Galary/Galary";
import axios from "axios";
import { Toaster } from "react-hot-toast";
import { UserContextProvider } from "../../context/userContext";


const inter = Inter({ subsets: ["latin"] });

axios.defaults.baseURL = 'http://localhost:8000'
axios.defaults.withCredentials = true

export default function Home() {
  return (
    <div className="innerwidth">
      <Head>
        <title>ECE-YiT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/YiT_logo.png" />
      </Head>
      <UserContextProvider>
      <section id="navbar">
        <NavBar />
      </section>
      <Toaster position="bottom-right" toastOptions={{duration: 2000}}/>
      <section id="homepage">
        <Homepage />
      </section>
      <section id="about">
        <About />
      </section>
      <section id="admission">
        <Admission />
      </section>
      <section id="department">
        <Department />
      </section>
      <section id="achivements">
        <Achivement />
      </section>
      <section id="contact">
        <Contact />
      </section>
      <section id="notes">
        <Notes />
      </section>
      <section id="galary">
        <Galary />
      </section>
      <section id="footer">
        <Footer />
      </section>
      </UserContextProvider>
    </div>
  );
}
